### ISSUE TITLE
Pitch change issues

### ISSUE THREAD

**Issue by gurs1kh** [adamrenklint/bap#45]
Increasing pitch works fine, but decreasing pitch works strangely. Increasing pitch by 100 gets you 100% higher pitch or one whole octave higher. Decreasing pitch by 50 should get you a 50% lower pitch or one octave lower, whereas -100 should get 0 since anything minus 100% is 0.
But the way that bap is implemented, -100 gives an octave lower.
I feel that in order to have consistency and in order to avoid having to create special cases for all octaves when decreasing, it is just better to do this:
-50: 1 octave decrease
-25: 2 octave decrease
etc.
This way, a simple formula can be used for pitch shift by half-steps: (Math.pow(2, steps / 12) - 1) \* 100.
The way it is currently implemented, every octave lower it is shifted, the number provided by this formula has to be doubled (*2 for any decrease, *4 after -1 octave, *8 after -2 octaves, etc).
Either that or you have to stick with hard-coded values for -11.225137463661294, -21.820256371932146, etc for every decrease, which isn't really the best way to go about doing it.

**Comment by gurs1kh** [comment]
Correction: decreasing an octave should actually by -50, since 100% decrease would make the pitch 0 and 50% would give half the frequency and thus an octave lower pitch

**Comment by adamrenklint** [comment]
Agreed, this clearly needs to be made simpler and consistent with how other attributes in Bap works.

What if it were instead absolute:
- -100: one octave decrease
- -200: two octaves decrease
- +100: one octave increase
- +300: three octaves increase

This feels like the simples API to deal with, and is consistent with how the _pan_ attribute works.

What do you think?

**Comment by gurs1kh** [comment]
I get why you want to do it that way, but that require either special cases for each octave, as the increase/decrease of each octave would require different cases in the client's code, as I kind of explained earlier.
However, doing it the following way makes it easier just to use this one formula: (Math.pow(2, steps / 12) - 1) \* 100
+100: 100% increase or pitch_2 or 1 octave increase
+300: 300% increase or pitch_4 or 2 octave increase
-50: 50% decrease or pitch / 2 or 1 octave decrease
-75: 75% decrease or pitch / 4 or 2 octave decrease
This is the way most software handles pitch shifts (also, bap's pitch increases already do it this way). See software such as Audacity or check out this page: https://www.mixxx.org/wiki/doku.php/pitch_percentages_for_semitones_and_notes

I personally would prefer using numbers to define the percentage of the original pitch. Ex: 100 for 0 pitch change, 50 for half the frequency/octave decrease, 25 for 2 octave decrease, 200 for twice the frequency or 1 octave up.
This is basically the same as the way I explained above, but with everything shifted up by 100.
I would prefer this so interval ratios can be easier to use. Ex: for a perfect fifth, you can just use 3/2 \* 100 or 150.
But in case someone is already relying on bap to working according to the way it is already defined, it may just be best to go with the original suggest and just have the pitch shifts go from -100 to +999 (or whatever the upper bound is). The interval ratios can still be used easily here, since all you have to do is subtract 100. Also, this way makes it easy to use the aforementioned formula to plug in semitones to get the amount to shift the pitch

**Comment by adamrenklint** [comment]
I'm worried that all these proposed solutions, as well as the current implementation, are failing to make the concept of changing the pitch straightforward to understand.

An alternate approach would be to split it into two attributes:
- `pitch` is the amount of semitones to increase or decrease, defaults to 0, valid values are -999 to 999 (theoretical limits)
- `detune` is the amount of cents to increase or decrease, defaults to 0, valid values are -99 to 99

With this approach it is still possible to composite the params of `note > channel > pattern > kit > slot > layer`, which is fundamental to Bap's architecture.

**Comment by adamrenklint** [comment]
Or could also be just a single attribute, which represents semitones, but with floats instead of integers. Finetuning/detuning with cents is then done with fractions/floats.

**Comment by gurs1kh** [comment]
Since each semitone has 100 cents each, having a float attribute for semitones shifted would probably be better than having two attributes. That way, if you want to add a cent, just use 0.01.
I really like this a lot better since I'm mainly using semitones for pitch shifting anyways.

However, certain clients may want to use exact ratios for certain things instead of equal tempered tuning (in case you don't know, here's a nice video to explain: https://www.youtube.com/watch?v=1Hqm0dYKUx4). For example, I'm planning on using equal tempered for overall tuning and exact ratios for some other things.
Because of this, I feel like some kind of setPitchByPercentage (probably needs a shorter name) function would also be nice, so that if I want a major third, I can just say setPitchByPercentage(5/4) instead of having to calculate how many semitones I would need exactly how many semitones I would need (in this case 3.86313714 instead of the equal tempered 4). Though this seems like a very nit-picky detail, it is very important if someone wants to create some kind of music teaching application where the exact pitch is important.

**Comment by gurs1kh** [comment]
Haven't heard back in a while? Any updates. Anything I may be able to help with?

**Comment by adamrenklint** [comment]
Hey, been tied up with another project 🔥 

What needs to happen:
- Change the `pitch` scale to semitones, like described in our two comments above
- Add a helper function to calculate exact pitch, probably directly on the main `bap` object

``` js
bap.pattern().channel(1).add(
  ['1.1.01', '1Q', 96, null, null, 0],            // no pitch shift
  ['1.2.01', '1Q', 96, null, null, -1],           // shift one semitone down
  ['1.3.01', '1Q', 96, null, null, -12],          // shift one octave down
  ['1.4.01', '1Q', 96, null, null, bap.pitchByPercentage(5/4)]
);
```

I'll try to get this in the next few weeks, but if you want to go ahead and make the change, I'd love to see a pull request 😄
As a hint, the spots that would need changing is https://github.com/adamrenklint/bap/blob/master/lib/Sample.js#L112 and https://github.com/adamrenklint/bap/blob/master/lib/Oscillator.js#L18, with tests at https://github.com/adamrenklint/bap/blob/master/test/lib/Sample.test.js#L11.

**Comment by gurs1kh** [comment]
I don't think the Oscillator needs to change since it is set by frequency directly and doesn't involve pitch-shifting

**Comment by adamrenklint** [comment]
I think the Oscillator still needs the same api, so that one could combine layers of oscillators and samples, and use the pitch attribute on a note to control them.
