### ISSUE TITLE
bundle.js is not on Github

### ISSUE THREAD

**Issue by benoitwimart** [adamrenklint/bap#58]
Hi,

To make examples works I added this file in /examples.
http://examples.bapjs.org/bundle.js

**Comment by adamrenklint** [comment]
`bundle.js` for the examples is a generated file, so it shouldn't be committed to version control. It is always generated fresh when you run `npm start` (https://github.com/adamrenklint/bap/blob/master/package.json#L83), with https://github.com/adamrenklint/bap/blob/master/examples/main.js as the bundle entry point.

**Comment by benoitwimart** [comment]
I work the old way : ) download the zip, unzip and launch a web server…
